webserver/cms/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path, include
# Wagtails CMS
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

# CMS
urlpatterns = [
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('', include(wagtail_urls)),
]

webserver/webserver/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
"""webserver URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import (
    handler404, handler500, handler403, url
)
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from solar_sizing_tool.views import SolarSizingToolView
from mmwave.views import (
    LOSCheckDemo, DSMExportView, LatestLidarView, NetworkDemoView
)
from dataUpdate.views import CountrySourceUpdatedView, ASNElasticSearchView, RDAPQueryView
from Overlay.views import OverlaySource
from IspToolboxAccounts.views import IntegrationTestAccountCreationView, UpdateNuxSettingView, CreateNewUserAccount
from workspace.views import (
     AdminGeneric403View, WorkspaceEngagementView, CeleryTaskPerformanceView, FlowerAsyncDashboardView
)
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include, re_path

from IspToolboxApp import views
from django.views.decorators.cache import cache_page
from django_js_reverse import views as reverse_views


# REST API Router
router = routers.DefaultRouter()

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    # Health Check Endpoint
    path('gis/osmBuildings/', views.BuildingsView.as_view(), name='osmBuildings'),
    # Market Evaluator
    # Pipeline Functions for MarketEvaluator
    path('market-evaluator/kmz/', views.MarketEvaluatorPipelineKMZ.as_view(),
         name='marketEvalKMZAsync'),  # ajax request from fb
    path('market-evaluator/export/',
         views.MarketEvaluatorExport.as_view(), name='export'),
    path('market-evaluator/export-np/', views.MarketEvaluatorExportNoPipeline.as_view(),
         name='exportnp'),  # ajax request from fb
    path('market-evaluator/test/',
         views.MarketEvaluatorTest.as_view(), name='market-eval-test'),
    # GeoTargeting Views
    path('marketing/audience/', views.MarketingAudienceView.as_view(),
         name="marketing_audience"),
    path('marketing/account/', views.MarketingAccountView.as_view(),
         name="marketing_account"),
    path('marketing/geocheck/', views.MarketingAudienceGeoPixelCheck.as_view(),
         name="marketing_geocheck"),
    # Marketing Pin Conversion Endpoints
    path('marketing/convert/', views.MarketingConvertPolygons.as_view()),
    # Path mmWave Planner
    path('mmwave-planner/', views.MMWavePlannerView.as_view(), name='mmwaveplanner'),
    path('help-center/', views.MMWaveHelpCenterView.as_view(),
         name='mmwaveplanner-helpcenter'),
    path('', include('mmwave.urls', namespace='mmwave')),
    # Path Overlay
    path('overlay/', OverlaySource.as_view(), name='overlay_source'),
    path('asn/', ASNElasticSearchView.as_view(), name="asn-search"),
    path('rdap/', RDAPQueryView.as_view(), name="rdap_query"),
    # Sources Last Updated Dates
    path('sources/last-update/', CountrySourceUpdatedView.as_view(),
         name='source_updated_dates'),
    # REST API Endpoints
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    # Workspace
    path('pro/', include('workspace.urls', namespace='workspace')),
    # Demo Views
    path('demo/solar-sizing-tool/',
         SolarSizingToolView.as_view(), name="demo-solar-sizing"),
    path('demo/los-check/', LOSCheckDemo.as_view(), name='demo-los-check'),
    path('demo/network-app/', NetworkDemoView.as_view(), name='demo-network-app'),
    path('demo/dsm-app/', DSMExportView.as_view(), name="demo-dsm-app"),
    path('demo/latest-gis-data/<int:year>/<int:month>/',
         LatestLidarView.as_view(), name='demo-latest_gis'),
    path('demo/latest-gis-data/', LatestLidarView.as_view(),
         name='demo-latest_gis-nodate'),
    # Redirect
    path('', views.HomepageRedirect.as_view()),
    # Django Hijack
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    # Integration Test Endpoints - be sure to 404 in prod
    path('test/accounts/', IntegrationTestAccountCreationView.as_view(),
         name="test-accounts"),
    path('test/accounts/login/', IntegrationTestAccountLoginView.as_view(), name="test-account-login"),
    # Feature Flipper
    url(r'^', include('waffle.urls')),

    # Accounts / All Auth
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="account_logout"),

    # New User Experiences - Admin Reset
    path('admin/update-nux/', UpdateNuxSettingView.as_view(), name="update-nux"),
    # Dashboard Paths
    path('admin/dashboard/', WorkspaceEngagementView.as_view(), name="admin-dashboard"),
    path('admin/celery/', CeleryTaskPerformanceView.as_view(), name="celery-summary"),
    re_path(r'async/.*', FlowerAsyncDashboardView.as_view(), name="async-dashboard"),
    # Admin User Creation
    path('admin/create-account/', CreateNewUserAccount.as_view(), name="admin-create-user"),

    # 403 Any request starting with admin
    re_path(r'admin/.*', AdminGeneric403View),

] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Facebook SDK Login

social_login = [
     path('fb-sdk/', include('allauth.socialaccount.providers.facebook.urls')),
     path('fb-sdk/social/', include('allauth.socialaccount.urls'))
]
urlpatterns += social_login

if settings.PROD:
    reverse_url = [
        path('reversejs/jsreverse.json',
             cache_page(3600)(reverse_views.urls_json), name='js_reverse_json'),
        path('reversejs/jsreverse.js',
             cache_page(3600)(reverse_views.urls_js), name='js_reverse'),
    ]
else:
    reverse_url = [
        path('reversejs/jsreverse.json',
             reverse_views.urls_json, name='js_reverse_json'),
        path('reversejs/jsreverse.js',
             reverse_views.urls_js, name='js_reverse'),
    ]

urlpatterns += reverse_url


if settings.PROD:
    # Admin SSO
    urlpatterns += [path('saml2/', include(('djangosaml2.urls', 'djangosaml2'), namespace='saml2'))]


handler500 = 'workspace.views.Error500View'  # noqa
handler404 = 'workspace.views.Error404View'  # noqa
handler403 = 'workspace.views.Error403View'  # noqa

webserver/workspace/api/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from workspace.api import views as api_views

app_name = "workspace.api"
urlpatterns = [
    path('token/', api_views.TokenInspectorView.as_view(), name='api-token'),
    path('docs/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'workspace:api:openapi-schema'}
    ), name='swagger-ui'),
    path('openapi', get_schema_view(
        title="ISP Toolbox API",
        description="ISP Toolbox API to access lidar tools",
        version="1.0.0"
    ), name='openapi-schema'),

    # V1
    path(
        'v1/ptp-serviceability/<uuid:uuid>/',
        api_views.PointToPointServiceabilityRetrieveDeleteView.as_view(),
        name="ptp-serviceability-get"
    ),
    path(
        'v1/ptp-serviceability/',
        api_views.PointToPointServiceabilityCreateView.as_view(),
        name="ptp-serviceability-create"
    ),
    path(
        'v1/ptp-serviceability/',
        api_views.PointToPointServiceabilityStopView.as_view(),
        name="ptp-serviceability-stop"
    ),
    path('v1/dummy-task/', api_views.DummyTaskCreateView.as_view(), name="dummy-task-create"),
    path(
            'v1/dummy-task/<uuid:uuid>/',
            api_views.DummyTaskRetrieveDeleteView.as_view(),
            name="dummy-task-retrieve-delete"
    ),
    path('v1/dummy-task/<uuid:uuid>/stop/', api_views.DummyTaskStopView.as_view(), name="dummy-task-stop"),
]

webserver/workspace/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path, include
from workspace import views
from mmwave.views import CreateExportDSM
from IspToolboxAccounts.views import CreateAccountView
from django.contrib.auth import views as auth_views
from IspToolboxAccounts import forms


app_name = 'workspace'
urlpatterns = [
    path('', views.WorkspaceDashboard.as_view(), name='workspace_dashboard'),
    path('signin/', views.DefaultWorkspaceView.as_view(), name="sign_up_workspace"),
    path('optional-info/', views.OptionalInfoWorkspaceView.as_view(),
         name="optional_info"),
    path('optional-info/update/', views.OptionalInfoWorkspaceUpdateView.as_view(),
         name="optional_info_update"),
    # LOS
    path('network/edit/<uuid:session_id>/',
         views.EditNetworkView.as_view(), name="edit_network_by_uuid"),
    path('network/edit/<uuid:session_id>/<str:name>/',
         views.EditNetworkView.as_view(), name="edit_network"),
    path('network/edit/', views.EditNetworkView.as_view(),
         name="edit_account_network"),
    # Market Evaluator
    path('market/<uuid:session_id>/export/',
         views.MarketEvaluatorSessionExportView.as_view(), name="market_eval_export"),
    path('market/<uuid:session_id>/', views.MarketEvaluatorView.as_view(), name="edit_market_by_uuid"),
    path('market/<uuid:session_id>/<str:name>/',
         views.MarketEvaluatorView.as_view(), name="market_eval"),
    path('market/', views.MarketEvaluatorView.as_view(), name="market_eval_entry"),
    # DSM Export
    path('workspace/api/dsm-export/', CreateExportDSM.as_view()),
    path('workspace/api/dsm-export/<uuid:uuid>/', CreateExportDSM.as_view()),
    # Marketing
    path('marketing/', views.ServiceabilityExportView.as_view(), name='serviceablility_export'),
    path('marketing/export/<uuid:uuid>.csv', views.ServiceabilityExportCsvView.as_view(), name="serviceability_export_csv"),
    # Sources
    path('sources/<str:sources_page>/',
         views.WorkspaceSourcesView.as_view(), name="sources"),
    # Account Creation and Management
    path(
        'accounts/sign-in/',
        auth_views.LoginView.as_view(
            template_name='workspace/pages/login_view.html',
            authentication_form=forms.IspToolboxUserAuthenticationForm,
            extra_context={
                'showSignUp': False,
                'authentication_form': forms.IspToolboxUserAuthenticationForm,
                'sign_up_form': forms.IspToolboxUserCreationForm,
            }
        ),
        name="login_view"
    ),
    path('workspace/account/',
         views.AccountSettingsView.as_view(), name="account_view"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout_view"),
    path('accounts/create/', CreateAccountView.as_view(),
         name="create_account_view"),
    path('account/delete/', views.DeleteYourInformationView.as_view(),
         name="delete_your_information"),
    path('account/access/', views.AccessYourInformationView.as_view(),
         name="access_your_information"),
    # Workspace Object Persistence
    path('workspace/api/ap-los/',
         views.AccessPointLocationListCreate.as_view(), name='ap'),
    path('workspace/api/ap-los/<uuid:uuid>/',
         views.AccessPointLocationGet.as_view(), name="get_ap_network"),
    path('workspace/api/cpe/', views.CPELocationCreate.as_view(), name="cpe"),
    path('workspace/api/cpe/<uuid:uuid>/', views.CPELocationGet.as_view()),
    path('workspace/api/ap-sector/', views.AccessPointSectorCreate.as_view(), name="ap_sector"),
    path('workspace/api/ap-sector/<uuid:uuid>/', views.AccessPointSectorGet.as_view()),
    path('workspace/api/ap-cpe-link/',
         views.APToCPELinkCreate.as_view(), name="ap-cpe-link"),
    path('workspace/api/ap-cpe-link/<uuid:uuid>/',
         views.APToCPELinkGet.as_view()),
    path('workspace/api/ptp-link/',
         views.PointToPointLinkCreate.as_view(), name="ptp-link"),
    path('workspace/api/ptp-link/<uuid:uuid>/',
         views.PointToPointLinkGet.as_view(), name="ptp-link-edit"),
    path('workspace/api/coverage-area/',
         views.CoverageAreaCreate.as_view(), name="coverage-area"),
    path('workspace/api/coverage-area/<uuid:uuid>/',
         views.CoverageAreaGet.as_view()),
    # Workspace
    path('workspace/api/ap-los/coverage/<uuid:uuid>/',
         views.AccessPointCoverageResults.as_view(), name="coverage-geojson"),
    path('workspace/api/ap-los/coverage/stats/<uuid:uuid>/',
         views.AccessPointCoverageStatsView.as_view(), name="coverage-stats"),
    path('workspace/api/tower/bulk-upload/',
         views.BulkUploadTowersView.as_view(), name="bulk_tower_upload"),
    path('workspace/api/session/<uuid:uuid>/',
         views.SessionCreateUpdateView.as_view(), name="session_update"),
    path('workspace/api/session/',
         views.SessionCreateUpdateView.as_view(), name="session_create"),
    path('workspace/api/session/download/<uuid:session_uuid>',
         views.SessionDownloadGeoJSONView.as_view(), name="session_download"),
    path('workspace/api/session/download/kml/<uuid:session_uuid>',
         views.SessionDownloadKMZView.as_view(), name="session_download_kmz"),
    path('workspace/api/session/save-as/',
         views.SessionSaveAsView.as_view(), name="session_saveas"),
    path('workspace/api/session/list/',
         views.SessionListView.as_view(), name="session_list"),
    path('workspace/api/session/delete/<uuid:uuid>/',
         views.SessionDeleteView.as_view(), name="session_delete"),
    # Forms
    path('workspace/form/ap-loc-form-<uuid:uuid>/',
         views.AccessPointLocationFormView.as_view(), name="ap-loc-form"),
    path('workspace/form/tower-form/<str:tool>/<uuid:uuid>/',
         views.TowerLocationFormView.as_view(), name="tower-form"),
    path('workspace/form/sector-form/<str:tool>/<uuid:uuid>/',
         views.SectorFormView.as_view(), name="sector-form"),
    path('workspace/form/sector-stats/<str:tool>/<uuid:uuid>/',
         views.SectorStatsView.as_view(), name="sector-stats"),
    path('workspace/form/cpe-forms/location/<uuid:session_id>/<str:lng>/<str:lat>/',
         views.LocationTooltipView.as_view(), name="los-location-form"),
    path('workspace/form/cpe-forms/cpe/<uuid:uuid>/',
         views.CPETooltipView.as_view(), name="cpe-form"),
    path('workspace/form/cpe-forms/sector-change/<uuid:session_id>/<str:lng>/<str:lat>/',
         views.SwitchSectorTooltipView.as_view(), name="cpe-switch-sector-form"),
    # Tables
    path('workspace/table/sessions/', views.SessionTableView.as_view(), name="session_table"),
    path('workspace/table/towers/', views.TowerTableView.as_view(), name="tower_table"),
    path('workspace/table/sectors/', views.SectorTableView.as_view(), name="sector_table"),
    path('workspace/table/serviceable/', views.SectorTableServiceableView.as_view(), name="sector_table_serviceable"),
    # Tables Update, Delete
    path('workspace/ajax/session/update/<uuid:pk>/', views.SessionUpdateView.as_view(), name="ajax_session_update"),
    path('workspace/ajax/session/create/', views.SessionCreateView.as_view(), name="ajax_session_create"),
    path('workspace/ajax/session/delete/<uuid:pk>/', views.SessionDeleteView.as_view(), name="ajax_session_delete"),
    path('workspace/ajax/tower/update/<uuid:pk>/', views.TowerUpdateView.as_view(), name="ajax_tower_update"),
    path('workspace/ajax/tower/create/<uuid:map_session>/', views.TowerCreateView.as_view(), name="ajax_tower_create"),
    path('workspace/ajax/tower/delete/<uuid:pk>/', views.TowerDeleteView.as_view(), name="ajax_tower_delete"),
    path('workspace/ajax/sector/update/<uuid:pk>/', views.SectorUpdateView.as_view(), name="ajax_sector_update"),
    path(
         'workspace/ajax/sector/create/<uuid:map_session>/<uuid:tower>/',
         views.SectorCreateView.as_view(),
         name="ajax_sector_create"
     ),
    path('workspace/ajax/sector/delete/<uuid:pk>/', views.SectorDeleteView.as_view(), name="ajax_sector_delete"),
    # Ajax
    path('workspace/ajax/ap-los/coverage/<uuid:uuid>/',
         views.AccessPointCoverageResults.as_view(), name="viewshed_coverage"),
    path('workspace/ajax/ap-los/coverage/stats/<uuid:uuid>/',
         views.AccessPointCoverageStatsView.as_view(), name="viewshed_stats"),
    path('workspace/ajax/ap-los/coverage/overlay/<uuid:uuid>/',
         views.AccessPointCoverageViewshedOverlayView.as_view(), name="viewshed_overlay"),
    path('workspace/ajax/session/sidebar/<uuid:uuid>/',
         views.ToolSidebarView.as_view(), name="sidebar_view"),
    # Analytics
    path('workspace/api/analytics/events/',
         views.AnalyticsView.as_view(), name='analytics'),
    path('workspace/api/analytics/network/interventions/',
         views.NetworkToolInterventionsView.as_view()),
    path('workspace/500/', views.Error500View, name='404'),
    # Potree Visualization
    path('workspace/api/visualization/<uuid:feature>/',
         views.PotreeVisualizationMetaView.as_view(), name="potree_viz"),
    # Workspace Session Import
    path('workspace/session/upload/',
         views.SessionFileImportView.as_view(), name='session_import_kmz'),
    # Facebook SDK Login
    path('fb/deauthorize-callback/',
         views.FBDeauthorizeSocialView.as_view(), name="fb_deauthorize"),
    path('fb/delete-callback/',
         views.FBDataDeletionView.as_view(), name="fb_deletion"),
    # Browseable API
    path('api/', include('workspace.api.urls', namespace='api')),

    # Multiplayer
    path('workspace/multiplayer/demo/',
         views.MultiplayerTestView.as_view(), name='multiplayer_demo'),
    path('workspace/multiplayer/demo/<uuid:session_id>/',
         views.MultiplayerTestView.as_view(), name='multiplayer_demo_uuid'),
    # Modals
    path('modals/market-eval-competitor-modal/',
         views.MarketEvaluatorCompetitorModalView.as_view()),
    # Tours
    path('workspace/tours/<str:tour_name>.js',

webserver/workspace/templates/workspace/atoms/account_dropdown.html
{% load i18n guest_user %}

<div class="account-dropdown" id="account-dropdown">
  {% if not user|is_guest_user %}
  <div class="dropdown show">
    <a
      href="#"
      role="button"
      id="dropdownMenuLink"
      data-toggle="dropdown"
      aria-haspopup="true"
      aria-expanded="false"
    >
      {% if user.socialaccount_set.all.0.get_avatar_url %}
      <img
        class="account-dropdown--picture mr-3"
        src="{{ user.socialaccount_set.all.0.get_avatar_url }}"
      />
      {% else %}
      <svg
        class="mr-3 my-auto"
        width="31"
        height="31"
        viewBox="0 0 31 31"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle cx="15.5" cy="15.5" r="15.5" fill="#C2D8EC" />
        <path
          d="M9.73682 21.0482C9.73682 17.9575 12.2422 15.4521 15.3329 15.4521H16.4521C19.5428 15.4521 22.0482 17.9575 22.0482 21.0482"
          stroke="#1172A9"
          stroke-width="2"
          stroke-miterlimit="10"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
        <path
          d="M15.8924 15.4521C17.7468 15.4521 19.2501 13.9489 19.2501 12.0945C19.2501 10.2401 17.7468 8.73682 15.8924 8.73682C14.0381 8.73682 12.5348 10.2401 12.5348 12.0945C12.5348 13.9489 14.0381 15.4521 15.8924 15.4521Z"
          stroke="#1172A9"
          stroke-width="2"
          stroke-miterlimit="10"
          stroke-linecap="round"
          stroke-linejoin="round"
        />
      </svg>
      {% endif %}
      <svg
        width="10"
        height="15"
        viewBox="0 0 8 5"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M1.35355 0.646447L1 0.292893L0.292893 1L0.646447 1.35355L1.35355 0.646447ZM4 4L3.64645 4.35355L4 4.70711L4.35355 4.35355L4 4ZM7.35355 1.35355L7.70711 1L7 0.292893L6.64645 0.646447L7.35355 1.35355ZM0.646447 1.35355L3.64645 4.35355L4.35355 3.64645L1.35355 0.646447L0.646447 1.35355ZM4.35355 4.35355L7.35355 1.35355L6.64645 0.646447L3.64645 3.64645L4.35355 4.35355Z"
          fill="black"
        />
      </svg>
    </a>
    <div
      class="dropdown-menu account-menu dropdown-menu-right"
      aria-labelledby="dropdownMenuLink"
    >
      <a class="dropdown-item" href="{% url 'workspace:account_view' %}"
        >{% translate "Manage Account"%}</a
      >
      <a class="dropdown-item" href="#">{% translate "Privacy/Terms"%}</a>
      {% if user.is_superuser %}
      <a class="dropdown-item" href="{% url 'admin:index' %}"
        >{% translate "admin (fb-only)"%}</a
      >
      {% endif %}
      <a
        class="dropdown-item"
        {% url 'workspace:workspace_dashboard' as next_url %}
        href="{% url 'workspace:logout_view' %}?next={{ next_url | urlencode}}"
        >{% translate "Logout"%}</a
      >
    </div>
  </div>
  {% else %} 
      <a href="#" data-toggle="modal" data-target="#importKMZModal">Upload File</a>
      &nbsp;or&nbsp;
      <a href="{% url 'workspace:login_view' %}?next={{request.get_full_path | urlencode}}">Sign In</a>
      &nbsp;to save your work.
  {% endif %}
</div>

webserver/workspace/templates/workspace/atoms/arrow_icon.html
<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg"
{% if flip %}
    transform="scale(1,-1)"
{% endif %}
>
        <path d="M9 5.5L5 9.5L1 5.5" 
    {% if light %}
        stroke="#D0D0D0"
    {% else %}
        stroke="#111111"
    {% endif %}
        stroke-linecap="round" stroke-linejoin="round" />
        <path d="M5 9.5V0.5" 
    {% if light %}
        stroke="#D0D0D0"
    {% else %}
        stroke="#111111"
    {% endif %}
        stroke-linecap="round" stroke-linejoin="round" />
</svg>

webserver/workspace/templates/workspace/atoms/coverage_stats_tower.html
{% load i18n %}

<div class="ap-stat">
    <p class="ap-stat--label">{% translate "Est. Clear LOS"%}<span>{% translate "at least 1 point on rooftop"%}</span></p>
    <p class="ap-stat--value" style="color: #34eb46;"><span class="ap-stat--icon mr-3">✅</span>{{coverage_stats.serviceable}}</p>
</div>
<div class="ap-stat">
    <p class="ap-stat--label">{% translate "Est. Obstructed LOS"%}</p>
    <p class="ap-stat--value" style="color: #ff2f00;"><span class="ap-stat--icon mr-3">🚫</span>{{coverage_stats.unserviceable}}</p>
</div>
{% if coverage_stats.unknown %}
<div class="ap-stat">
    <p class="ap-stat--label">{% translate "Est. Calculating / Unknown"%}</p>
    <p class="ap-stat--value" style="color: #ccc;"><span class="ap-stat--icon mr-3">🤷‍♀️</span>{{coverage_stats.unknown}}</p>
</div>
{% endif %}

webserver/workspace/templates/workspace/atoms/pen_icon.html
<svg width="19" height="16" viewBox="0 0 19 16" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g >
        <path d="M12.1515 3L15.5194 6" stroke="#1172A9" stroke-miterlimit="10" stroke-linecap="round"
            stroke-linejoin="round" />
        <path d="M14.3967 1L17.7646 4L6.53831 14L2.04779 15L3.17042 11L14.3967 1Z" stroke="#1172A9"
            stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round" />
    </g>
</svg>

webserver/workspace/templates/workspace/atoms/screen_size_logging.html
{% csrf_token %}
<script>
  const screen_size = {};
  $(() => {
    const screen_size = [];
    if (window) {
      if (window.screen) {
        screen_size.push(window.screen.width);
        screen_size.push(window.screen.height);
        screen_size.push(window.screen.availWidth);
        screen_size.push(window.screen.availHeight);
      }
      screen_size.push(window.innerWidth);
      screen_size.push(window.innerHeight);
      screen_size.push(window.devicePixelRatio);
    }
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    $.post({
      url: "{% url 'workspace:analytics' %}",
      data: JSON.stringify({url: window.location.pathname, eventType: 'screen_dim', sessionId: JSON.stringify(screen_size) }),
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrftoken
      }
    });
  });
</script>

webserver/workspace/templates/workspace/atoms/seo_headers.html
{% load i18n %}
{% if description %}
<meta name="description" content="{% translate description%}"/>
{% endif %}