webserver/cms/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path, include
# Wagtails CMS
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

# CMS
urlpatterns = [
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('', include(wagtail_urls)),
]

webserver/webserver/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
"""webserver URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import (
    handler404, handler500, handler403, url
)
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from solar_sizing_tool.views import SolarSizingToolView
from mmwave.views import (
    LOSCheckDemo, DSMExportView, LatestLidarView, NetworkDemoView
)
from dataUpdate.views import CountrySourceUpdatedView, ASNElasticSearchView, RDAPQueryView
from Overlay.views import OverlaySource
from IspToolboxAccounts.views import IntegrationTestAccountCreationView, UpdateNuxSettingView, CreateNewUserAccount
from workspace.views import (
     AdminGeneric403View, WorkspaceEngagementView, CeleryTaskPerformanceView, FlowerAsyncDashboardView
)
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include, re_path

from IspToolboxApp import views
from django.views.decorators.cache import cache_page
from django_js_reverse import views as reverse_views


# REST API Router
router = routers.DefaultRouter()

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    # Health Check Endpoint
    path('gis/osmBuildings/', views.BuildingsView.as_view(), name='osmBuildings'),
    # Market Evaluator
    # Pipeline Functions for MarketEvaluator
    path('market-evaluator/kmz/', views.MarketEvaluatorPipelineKMZ.as_view(),
         name='marketEvalKMZAsync'),  # ajax request from fb
    path('market-evaluator/export/',
         views.MarketEvaluatorExport.as_view(), name='export'),
    path('market-evaluator/export-np/', views.MarketEvaluatorExportNoPipeline.as_view(),
         name='exportnp'),  # ajax request from fb
    path('market-evaluator/test/',
         views.MarketEvaluatorTest.as_view(), name='market-eval-test'),
    # GeoTargeting Views
    path('marketing/audience/', views.MarketingAudienceView.as_view(),
         name="marketing_audience"),
    path('marketing/account/', views.MarketingAccountView.as_view(),
         name="marketing_account"),
    path('marketing/geocheck/', views.MarketingAudienceGeoPixelCheck.as_view(),
         name="marketing_geocheck"),
    # Marketing Pin Conversion Endpoints
    path('marketing/convert/', views.MarketingConvertPolygons.as_view()),
    # Path mmWave Planner
    path('mmwave-planner/', views.MMWavePlannerView.as_view(), name='mmwaveplanner'),
    path('help-center/', views.MMWaveHelpCenterView.as_view(),
         name='mmwaveplanner-helpcenter'),
    path('', include('mmwave.urls', namespace='mmwave')),
    # Path Overlay
    path('overlay/', OverlaySource.as_view(), name='overlay_source'),
    path('asn/', ASNElasticSearchView.as_view(), name="asn-search"),
    path('rdap/', RDAPQueryView.as_view(), name="rdap_query"),
    # Sources Last Updated Dates
    path('sources/last-update/', CountrySourceUpdatedView.as_view(),
         name='source_updated_dates'),
    # REST API Endpoints
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    # Workspace
    path('pro/', include('workspace.urls', namespace='workspace')),
    # Demo Views
    path('demo/solar-sizing-tool/',
         SolarSizingToolView.as_view(), name="demo-solar-sizing"),
    path('demo/los-check/', LOSCheckDemo.as_view(), name='demo-los-check'),
    path('demo/network-app/', NetworkDemoView.as_view(), name='demo-network-app'),
    path('demo/dsm-app/', DSMExportView.as_view(), name="demo-dsm-app"),
    path('demo/latest-gis-data/<int:year>/<int:month>/',
         LatestLidarView.as_view(), name='demo-latest_gis'),
    path('demo/latest-gis-data/', LatestLidarView.as_view(),
         name='demo-latest_gis-nodate'),
    # Redirect
    path('', views.HomepageRedirect.as_view()),
    # Django Hijack
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),
    # Integration Test Endpoints - be sure to 404 in prod
    path('test/accounts/', IntegrationTestAccountCreationView.as_view(),
         name="test-accounts"),
    path('test/accounts/login/', IntegrationTestAccountLoginView.as_view(), name="test-account-login"),
    # Feature Flipper
    url(r'^', include('waffle.urls')),

    # Accounts / All Auth
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="account_logout"),

    # New User Experiences - Admin Reset
    path('admin/update-nux/', UpdateNuxSettingView.as_view(), name="update-nux"),
    # Dashboard Paths
    path('admin/dashboard/', WorkspaceEngagementView.as_view(), name="admin-dashboard"),
    path('admin/celery/', CeleryTaskPerformanceView.as_view(), name="celery-summary"),
    re_path(r'async/.*', FlowerAsyncDashboardView.as_view(), name="async-dashboard"),
    # Admin User Creation
    path('admin/create-account/', CreateNewUserAccount.as_view(), name="admin-create-user"),

    # 403 Any request starting with admin
    re_path(r'admin/.*', AdminGeneric403View),

] + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# Facebook SDK Login

social_login = [
     path('fb-sdk/', include('allauth.socialaccount.providers.facebook.urls')),
     path('fb-sdk/social/', include('allauth.socialaccount.urls'))
]
urlpatterns += social_login

if settings.PROD:
    reverse_url = [
        path('reversejs/jsreverse.json',
             cache_page(3600)(reverse_views.urls_json), name='js_reverse_json'),
        path('reversejs/jsreverse.js',
             cache_page(3600)(reverse_views.urls_js), name='js_reverse'),
    ]
else:
    reverse_url = [
        path('reversejs/jsreverse.json',
             reverse_views.urls_json, name='js_reverse_json'),
        path('reversejs/jsreverse.js',
             reverse_views.urls_js, name='js_reverse'),
    ]

urlpatterns += reverse_url


if settings.PROD:
    # Admin SSO
    urlpatterns += [path('saml2/', include(('djangosaml2.urls', 'djangosaml2'), namespace='saml2'))]


handler500 = 'workspace.views.Error500View'  # noqa
handler404 = 'workspace.views.Error404View'  # noqa
handler403 = 'workspace.views.Error403View'  # noqa

webserver/workspace/api/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path
from django.views.generic import TemplateView
from rest_framework.schemas import get_schema_view
from workspace.api import views as api_views

app_name = "workspace.api"
urlpatterns = [
    path('token/', api_views.TokenInspectorView.as_view(), name='api-token'),
    path('docs/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'workspace:api:openapi-schema'}
    ), name='swagger-ui'),
    path('openapi', get_schema_view(
        title="ISP Toolbox API",
        description="ISP Toolbox API to access lidar tools",
        version="1.0.0"
    ), name='openapi-schema'),

    # V1
    path(
        'v1/ptp-serviceability/<uuid:uuid>/',
        api_views.PointToPointServiceabilityRetrieveDeleteView.as_view(),
        name="ptp-serviceability-get"
    ),
    path(
        'v1/ptp-serviceability/',
        api_views.PointToPointServiceabilityCreateView.as_view(),
        name="ptp-serviceability-create"
    ),
    path(
        'v1/ptp-serviceability/',
        api_views.PointToPointServiceabilityStopView.as_view(),
        name="ptp-serviceability-stop"
    ),
    path('v1/dummy-task/', api_views.DummyTaskCreateView.as_view(), name="dummy-task-create"),
    path(
            'v1/dummy-task/<uuid:uuid>/',
            api_views.DummyTaskRetrieveDeleteView.as_view(),
            name="dummy-task-retrieve-delete"
    ),
    path('v1/dummy-task/<uuid:uuid>/stop/', api_views.DummyTaskStopView.as_view(), name="dummy-task-stop"),
]

webserver/workspace/urls.py
# (c) Meta Platforms, Inc. and affiliates. Copyright
from django.urls import path, include
from workspace import views
from mmwave.views import CreateExportDSM
from IspToolboxAccounts.views import CreateAccountView
from django.contrib.auth import views as auth_views
from IspToolboxAccounts import forms


app_name = 'workspace'
urlpatterns = [
    path('', views.WorkspaceDashboard.as_view(), name='workspace_dashboard'),
    path('signin/', views.DefaultWorkspaceView.as_view(), name="sign_up_workspace"),
    path('optional-info/', views.OptionalInfoWorkspaceView.as_view(),
         name="optional_info"),
    path('optional-info/update/', views.OptionalInfoWorkspaceUpdateView.as_view(),
         name="optional_info_update"),
    # LOS
    path('network/edit/<uuid:session_id>/',
         views.EditNetworkView.as_view(), name="edit_network_by_uuid"),
    path('network/edit/<uuid:session_id>/<str:name>/',
         views.EditNetworkView.as_view(), name="edit_network"),
    path('network/edit/', views.EditNetworkView.as_view(),
         name="edit_account_network"),
    # Market Evaluator
    path('market/<uuid:session_id>/export/',
         views.MarketEvaluatorSessionExportView.as_view(), name="market_eval_export"),
    path('market/<uuid:session_id>/', views.MarketEvaluatorView.as_view(), name="edit_market_by_uuid"),
    path('market/<uuid:session_id>/<str:name>/',
         views.MarketEvaluatorView.as_view(), name="market_eval"),
    path('market/', views.MarketEvaluatorView.as_view(), name="market_eval_entry"),
    # DSM Export
    path('workspace/api/dsm-export/', CreateExportDSM.as_view()),
    path('workspace/api/dsm-export/<uuid:uuid>/', CreateExportDSM.as_view()),
    # Marketing
    path('marketing/', views.ServiceabilityExportView.as_view(), name='serviceablility_export'),
    path('marketing/export/<uuid:uuid>.csv', views.ServiceabilityExportCsvView.as_view(), name="serviceability_export_csv"),
    # Sources
    path('sources/<str:sources_page>/',
         views.WorkspaceSourcesView.as_view(), name="sources"),
    # Account Creation and Management
    path(
        'accounts/sign-in/',
        auth_views.LoginView.as_view(
            template_name='workspace/pages/login_view.html',
            authentication_form=forms.IspToolboxUserAuthenticationForm,
            extra_context={
                'showSignUp': False,
                'authentication_form': forms.IspToolboxUserAuthenticationForm,
                'sign_up_form': forms.IspToolboxUserCreationForm,
            }
        ),
        name="login_view"
    ),
    path('workspace/account/',
         views.AccountSettingsView.as_view(), name="account_view"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout_view"),
    path('accounts/create/', CreateAccountView.as_view(),
         name="create_account_view"),
    path('account/delete/', views.DeleteYourInformationView.as_view(),
         name="delete_your_information"),
    path('account/access/', views.AccessYourInformationView.as_view(),
         name="access_your_information"),
    # Workspace Object Persistence
    path('workspace/api/ap-los/',
         views.AccessPointLocationListCreate.as_view(), name='ap'),
    path('workspace/api/ap-los/<uuid:uuid>/',
         views.AccessPointLocationGet.as_view(), name="get_ap_network"),
    path('workspace/api/cpe/', views.CPELocationCreate.as_view(), name="cpe"),
    path('workspace/api/cpe/<uuid:uuid>/', views.CPELocationGet.as_view()),
    path('workspace/api/ap-sector/', views.AccessPointSectorCreate.as_view(), name="ap_sector"),
    path('workspace/api/ap-sector/<uuid:uuid>/', views.AccessPointSectorGet.as_view()),
    path('workspace/api/ap-cpe-link/',
         views.APToCPELinkCreate.as_view(), name="ap-cpe-link"),
    path('workspace/api/ap-cpe-link/<uuid:uuid>/',
         views.APToCPELinkGet.as_view()),
    path('workspace/api/ptp-link/',
         views.PointToPointLinkCreate.as_view(), name="ptp-link"),
    path('workspace/api/ptp-link/<uuid:uuid>/',
         views.PointToPointLinkGet.as_view(), name="ptp-link-edit"),
    path('workspace/api/coverage-area/',
         views.CoverageAreaCreate.as_view(), name="coverage-area"),
    path('workspace/api/coverage-area/<uuid:uuid>/',
         views.CoverageAreaGet.as_view()),
    # Workspace
    path('workspace/api/ap-los/coverage/<uuid:uuid>/',
         views.AccessPointCoverageResults.as_view(), name="coverage-geojson"),
    path('workspace/api/ap-los/coverage/stats/<uuid:uuid>/',
         views.AccessPointCoverageStatsView.as_view(), name="coverage-stats"),
    path('workspace/api/tower/bulk-upload/',
         views.BulkUploadTowersView.as_view(), name="bulk_tower_upload"),
    path('workspace/api/session/<uuid:uuid>/',
         views.SessionCreateUpdateView.as_view(), name="session_update"),
    path('workspace/api/session/',
         views.SessionCreateUpdateView.as_view(), name="session_create"),
    path('workspace/api/session/download/<uuid:session_uuid>',
         views.SessionDownloadGeoJSONView.as_view(), name="session_download"),
    path('workspace/api/session/download/kml/<uuid:session_uuid>',
         views.SessionDownloadKMZView.as_view(), name="session_download_kmz"),
    path('workspace/api/session/save-as/',
         views.SessionSaveAsView.as_view(), name="session_saveas"),
    path('workspace/api/session/list/',
         views.SessionListView.as_view(), name="session_list"),
    path('workspace/api/session/delete/<uuid:uuid>/',
         views.SessionDeleteView.as_view(), name="session_delete"),
    # Forms
    path('workspace/form/ap-loc-form-<uuid:uuid>/',
         views.AccessPointLocationFormView.as_view(), name="ap-loc-form"),
    path('workspace/form/tower-form/<str:tool>/<uuid:uuid>/',
         views.TowerLocationFormView.as_view(), name="tower-form"),
    path('workspace/form/sector-form/<str:tool>/<uuid:uuid>/',
         views.SectorFormView.as_view(), name="sector-form"),
    path('workspace/form/sector-stats/<str:tool>/<uuid:uuid>/',
         views.SectorStatsView.as_view(), name="sector-stats"),
    path('workspace/form/cpe-forms/location/<uuid:session_id>/<str:lng>/<str:lat>/',
         views.LocationTooltipView.as_view(), name="los-location-form"),
    path('workspace/form/cpe-forms/cpe/<uuid:uuid>/',
         views.CPETooltipView.as_view(), name="cpe-form"),
    path('workspace/form/cpe-forms/sector-change/<uuid:session_id>/<str:lng>/<str:lat>/',
         views.SwitchSectorTooltipView.as_view(), name="cpe-switch-sector-form"),
    # Tables
    path('workspace/table/sessions/', views.SessionTableView.as_view(), name="session_table"),
    path('workspace/table/towers/', views.TowerTableView.as_view(), name="tower_table"),
    path('workspace/table/sectors/', views.SectorTableView.as_view(), name="sector_table"),
    path('workspace/table/serviceable/', views.SectorTableServiceableView.as_view(), name="sector_table_serviceable"),
    # Tables Update, Delete
    path('workspace/ajax/session/update/<uuid:pk>/', views.SessionUpdateView.as_view(), name="ajax_session_update"),
    path('workspace/ajax/session/create/', views.SessionCreateView.as_view(), name="ajax_session_create"),
    path('workspace/ajax/session/delete/<uuid:pk>/', views.SessionDeleteView.as_view(), name="ajax_session_delete"),
    path('workspace/ajax/tower/update/<uuid:pk>/', views.TowerUpdateView.as_view(), name="ajax_tower_update"),
    path('workspace/ajax/tower/create/<uuid:map_session>/', views.TowerCreateView.as_view(), name="ajax_tower_create"),
    path('workspace/ajax/tower/delete/<uuid:pk>/', views.TowerDeleteView.as_view(), name="ajax_tower_delete"),
    path('workspace/ajax/sector/update/<uuid:pk>/', views.SectorUpdateView.as_view(), name="ajax_sector_update"),
    path(
         'workspace/ajax/sector/create/<uuid:map_session>/<uuid:tower>/',
         views.SectorCreateView.as_view(),
         name="ajax_sector_create"
     ),
    path('workspace/ajax/sector/delete/<uuid:pk>/', views.SectorDeleteView.as_view(), name="ajax_sector_delete"),
    # Ajax
    path('workspace/ajax/ap-los/coverage/<uuid:uuid>/',
         views.AccessPointCoverageResults.as_view(), name="viewshed_coverage"),
    path('workspace/ajax/ap-los/coverage/stats/<uuid:uuid>/',
         views.AccessPointCoverageStatsView.as_view(), name="viewshed_stats"),
    path('workspace/ajax/ap-los/coverage/overlay/<uuid:uuid>/',
         views.AccessPointCoverageViewshedOverlayView.as_view(), name="viewshed_overlay"),
    path('workspace/ajax/session/sidebar/<uuid:uuid>/',
         views.ToolSidebarView.as_view(), name="sidebar_view"),
    # Analytics
    path('workspace/api/analytics/events/',
         views.AnalyticsView.as_view(), name='analytics'),
    path('workspace/api/analytics/network/interventions/',
         views.NetworkToolInterventionsView.as_view()),
    path('workspace/500/', views.Error500View, name='404'),
    # Potree Visualization
    path('workspace/api/visualization/<uuid:feature>/',
         views.PotreeVisualizationMetaView.as_view(), name="potree_viz"),
    # Workspace Session Import
    path('workspace/session/upload/',
         views.SessionFileImportView.as_view(), name='session_import_kmz'),
    # Facebook SDK Login
    path('fb/deauthorize-callback/',
         views.FBDeauthorizeSocialView.as_view(), name="fb_deauthorize"),
    path('fb/delete-callback/',
         views.FBDataDeletionView.as_view(), name="fb_deletion"),
    # Browseable API
    path('api/', include('workspace.api.urls', namespace='api')),

    # Multiplayer
    path('workspace/multiplayer/demo/',
         views.MultiplayerTestView.as_view(), name='multiplayer_demo'),
    path('workspace/multiplayer/demo/<uuid:session_id>/',
         views.MultiplayerTestView.as_view(), name='multiplayer_demo_uuid'),
    # Modals
    path('modals/market-eval-competitor-modal/',
         views.MarketEvaluatorCompetitorModalView.as_view()),
    # Tours
    path('workspace/tours/<str:tour_name>.js',

webserver/workspace/templates/workspace/molecules/draw_controls.html
<div class="btn-group draw-controls" role="group" aria-label="Drawing Controls" id="drawing-controls">
  {% if tool == "market_evaluator" %}
    {% include "workspace/atoms/buttons/draw_coverage_area_base.html" %}
    {% include "workspace/atoms/buttons/place_tower_button_base.html" %}
  {% elif tool == "los_check" %}
  {% include "workspace/atoms/buttons/draw_ptp_link_button_base.html" %}
    {% if not ptponly %}
    {% include "mmwave/atoms/buttons/place_tower_button.html" %}
    {% endif %}
  {% endif %}
</div>

webserver/workspace/templates/workspace/molecules/tool_drawer_top.html
{% load static i18n %}

<div class="py-4 pl-4 pr-5">
    <div class="accordion" id="accordionExample">
        <div role="dropdown" aria-label="Business Tools Dropdown" class="mb-4">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                data-target="#collapseBusinessTools" aria-expanded="true" aria-controls="collapseBusinessTools">
                {% translate "Business Tools"%}
                <svg width="8" height="5" style="margin-left: 6px;" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M1.354.646L1 .293.293 1l.353.354.708-.708zM4 4l-.354.354.354.353.354-.353L4 4zm3.354-2.646L7.707 1 7 .293l-.354.353.708.708zm-6.708 0l3 3 .708-.708-3-3-.708.708zm3.708 3l3-3-.708-.708-3 3 .708.708z"
                        fill="#000"></path>
                </svg>
            </button>
            <div id="collapseBusinessTools" class="collapse {% if tool == 'market_evaluator' %}show{% endif %}"
                aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="ml-5 mt-2 nested-options">
                    <div class="mb-3">
                        <a href="https://www.facebook.com/isptoolbox/roi-estimator/">
                            {% translate "ROI Estimator"%}
                            <svg class="link-arrow" width="15" height="11" viewBox="0 0 15 11" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 5.5H13.6216M10.2162 1L14 5.5L10.2162 10" stroke="#1172A9" />
                            </svg>
                        </a>
                        <p class="tool-description">
                            {% translate "View Potential return on investment"%}
                        </p>
                    </div>
                    <div>
                        <a href="{% url 'workspace:market_eval_entry' %}">
                            {% translate "Market Evaluator"%}
                            <svg class="link-arrow" width="15" height="11" viewBox="0 0 15 11" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 5.5H13.6216M10.2162 1L14 5.5L10.2162 10" stroke="#1172A9" />
                            </svg>
                        </a>
                        <p class="tool-description">
                            {% translate "Evaluate how many customers are in a service area"%}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div role="dropdown" aria-label="Network Tools Dropdown" class="my-4">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                data-target="#collapseNetworkTools" aria-expanded="true" aria-controls="collapseNetworkTools">
                {% translate "Network Tools"%}
                <svg width="8" height="5" style="margin-left: 6px;" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M1.354.646L1 .293.293 1l.353.354.708-.708zM4 4l-.354.354.354.353.354-.353L4 4zm3.354-2.646L7.707 1 7 .293l-.354.353.708.708zm-6.708 0l3 3 .708-.708-3-3-.708.708zm3.708 3l3-3-.708-.708-3 3 .708.708z"
                        fill="#000"></path>
                </svg>
            </button>
            <div id="collapseNetworkTools" class="collapse {% if tool == 'network' %}show{% endif %}"
                aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="ml-5 mt-2 nested-options">
                    <div>
                        <a href="{% url 'workspace:edit_account_network' %}">
                            {% translate "LiDAR LOS Check"%}
                            <svg class="link-arrow" width="15" height="11" viewBox="0 0 15 11" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 5.5H13.6216M10.2162 1L14 5.5L10.2162 10" stroke="#1172A9" />
                            </svg>
                        </a>
                        <p class="tool-description">
                            {% translate "Use LiDAR data to determine if a customer is serviceable"%}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div role="dropdown" aria-label="Marketing Tools Dropdown" class="my-4">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                data-target="#collapseMarketingTools" aria-expanded="true" aria-controls="collapseMarketingTools">
                {% translate "Marketing Tools"%}
                <svg width="8" height="5" style="margin-left: 6px;" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M1.354.646L1 .293.293 1l.353.354.708-.708zM4 4l-.354.354.354.353.354-.353L4 4zm3.354-2.646L7.707 1 7 .293l-.354.353.708.708zm-6.708 0l3 3 .708-.708-3-3-.708.708zm3.708 3l3-3-.708-.708-3 3 .708.708z"
                        fill="#000"></path>
                </svg>
            </button>

            <div id="collapseMarketingTools" class="collapse {% if tool == 'marketing' %}show{% endif %}"
                aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="ml-5 mt-2 nested-options">
                    <div>
                        <a href="https://www.facebook.com/isptoolbox/marketing/">
                            {% translate "Service Area Ads"%}
                            <svg class="link-arrow" width="15" height="11" viewBox="0 0 15 11" fill="none"
                                xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 5.5H13.6216M10.2162 1L14 5.5L10.2162 10" stroke="#1172A9" />
                            </svg>
                        </a>
                        <p class="tool-description">
                            {% translate "Generate Custom Audiences for Facebook Marketing."%}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div role="dropdown" aria-label="Learn &amp; Connect Dropdown" class="my-4">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse"
                data-target="#collapseLearnAndConnect" aria-expanded="true" aria-controls="collapseLearnAndConnect">
                {% translate "Learn &amp; Connect"%}
                <svg width="8" height="5" style="margin-left: 6px;" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path
                        d="M1.354.646L1 .293.293 1l.353.354.708-.708zM4 4l-.354.354.354.353.354-.353L4 4zm3.354-2.646L7.707 1 7 .293l-.354.353.708.708zm-6.708 0l3 3 .708-.708-3-3-.708.708zm3.708 3l3-3-.708-.708-3 3 .708.708z"
                        fill="#000"></path>
                </svg>
            </button>

            <div id="collapseLearnAndConnect" class="collapse" aria-labelledby="headingOne"
                data-parent="#accordionExample">
                <div class="ml-5 mt-2 mr-2 nested-options">
                    <a target="_blank" href="https://www.facebook.com/fbctoolbox" aria-label="Toolbox Program Link">ISP
                        Toolbox Program</a>
                    <a target="_blank" href="https://www.facebook.com/groups/1877902682340586/"
                        aria-label="WISP Bootcamp Link">WISP Bootcamp</a>
                    <a target="_blank" href="https://www.facebook.com/groups/3107359779316518/"
                        aria-label="WISP Jobs Link">WISP Jobs</a>
                    <a target="_blank" href="https://www.facebook.com/groups/wisptalk/" aria-label="Wisp Talk Link">Wisp
                        Talk</a>
                </div>
            </div>
        </div>
    </div>

</div>

webserver/workspace/templates/workspace/molecules/tower_tooltip_form_base.html
{% spaceless %}
<div class="tooltip--sector-summary">
    <div class="title"> 
        <p>
            {% block title %} Edit Tower {% endblock %}
        </p>
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
</div>
{% endspaceless %}